image:
  file: .gitpod.Dockerfile

tasks:
  - name: install java, kotlin
    command: |
      echo "y" | sdk install java 17.0.8.fx-zulu # instead of "-y"
      sdk install kotlin 1.8.20
      sdk use kotlin 1.8.20 --default

  - name: mkd; command of make first direcotory
    command: |
      export PATH=$PATH:/workspace/atcoder-contests/command

  - name: install oj and login
    command: |
      pip3 install online-judge-tools

vscode:
  extensions:
    - fwcd.kotlin
    - mathiasfrohlich.Kotlin
    - vscjava.vscode-java-pack
