image:
  file: .gitpod.Dockerfile

tasks:
  - name: install java, kotlin
    command: |
      sdk install java 17.0.8.fx-zulu
      sdk use java 17.0.8.fx-zulu --default
      sdk install kotlin 1.8.20
      sdk use kotlin 1.8.20 --default

  - name: mkd; command of make first direcotory
    command: |
      export PATH=$PATH:/workspace/atcoder-java/command

vscode:
  extensions:
    - fwcd.kotlin
    - mathiasfrohlich.Kotlin
    - vscjava.vscode-java-pack
