#!/bin/bash
if [[ $1 = "-h" ]]; then
  echo "$(basename $0) is custom command"
  echo "Usage : \"kotc Main.kt\" then compile Main.kt and create Main.jar in current directory"
  echo ""
  exit 0
fi


readonly fileWithExt=$1
readonly file=${fileWithExt%\.kt}

if [ $fileWithExt = "" ]; then
  echo "Error : Requires an argument" 1>&2
  exit 1
fi

echo $fileWithExt | grep -E ".+\.kt$" > /dev/null 2>&1
if [ $? -eq 1 ]; then
  echo "Error : ${fileWithExt} is not kotlin file" 1>&2
  exit 2
fi

kotlinc $fileWithExt -include-runtime -d ${file}.jar

exit 0
