#!/bin/bash

readonly dir=$1


if [[ $dir = "" ]]; then
  echo "Error : Requires an argument" 1>&2
  exit 1
elif [ -e ${dir} ]; then
  echo `Error : ${dir} is already exist` 1>&2
  exit 2
fi

mkdir ${dir}/
cd ${dir} && mkdir a_1 b_1 c_1

exit 0
