#!/bin/bash

# ヘルプオプション
if [[ $1 = "-h" ]]; then
  echo "$(basename $0) is custom command"
  echo "Usage : \"mkd 314\"  then create below folders"
  echo "    314/"
  echo "      ├─ a_1/"
  echo "      ├─ b_1/"
  echo "      └─ c_1/"
  echo ""
  exit 0
fi


readonly dir=$1

# 引数チェック
if [[ $dir = "" ]]; then
  echo "Error : Requires an argument" 1>&2
  exit 1
elif [ -e ${dir} ]; then
  echo `Error : ${dir} is already exist` 1>&2
  exit 2
fi

# 問題毎のディレクトリ作成
mkdir ${dir}/
cd ${dir} && mkdir a_1 b_1 c_1

exit 0
